# Generated by Django 4.0.1 on 2022-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('RegisterNumber', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Grade', models.CharField(max_length=120)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
    ]
